language: generic

sudo: required

services:
  - docker

before-install:
  - docker build -t voort66/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true voort66/docker-react npm run test
